/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EsPwsqkAVia
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

'use client'
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useRouter } from 'next/navigation'
import {useRef, useState} from 'react';

export function Home() {
  const inputRef = useRef<HTMLInputElement>(null);
  const router = useRouter();
  const [value, setValue] = useState<string|undefined>(undefined);

  return (
    <>
      <div className="w-full bg-gradient-to-b from-[#F5F5F5] to-white dark:from-[#1F2937] dark:to-[#111827] py-12 md:py-16 lg:py-20">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-4xl md:text-5xl">
              Find the best beauty products and services
            </h1>
            <p className="mt-4 text-lg text-gray-600 dark:text-gray-400">
              Search through thousands of beauty products and services to find the perfect fit for you.
            </p>
            <div className="mt-8 flex justify-center">
              <div className="relative w-full max-w-lg">
                <Input
                  className="w-full rounded-full border border-gray-200 border-gray-300 px-4 py-3 pr-12 text-gray-900 shadow-sm focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-700 dark:bg-gray-800 dark:text-white dark:focus:border-gray-900 dark:border-gray-800 dark:focus:border-gray-50 dark:focus:ring-gray-50 dark:dark:focus:border-gray-50"
                  placeholder="Search for beauty products, services, and more..."
                  type="search"
                  ref={inputRef}
                  onChange={(e) => {
                    if(e.currentTarget.value) {
                      setValue(e.currentTarget.value)
                    }
                  }}
                />
                <Button
                  className="absolute right-1 top-1 h-10 w-10 rounded-full bg-gray-900 text-white focus:outline-none focus:ring-2 focus:ring-gray-900 focus:ring-offset-2 dark:focus:ring-offset-gray-800 dark:bg-gray-50 dark:focus:ring-gray-50"
                  type="submit"
                  onClick={() => {
                    if(value) {
                      router.push(`/search/${value}`);
                    }
                  }}
                >
                  <SearchIcon className="h-5 w-5" />
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="container px-4 md:px-6 py-12 md:py-16 lg:py-20">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="group rounded-lg bg-white p-6 shadow-sm transition-all hover:shadow-md dark:bg-gray-800">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="h-12 w-12 rounded-full bg-[#FEF2F2] p-2.5 text-[#EF4444] dark:bg-[#1F2937] dark:text-[#EF4444]">
                  <PaintbrushIcon className="h-7 w-7" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Makeup</h3>
              </div>
              <Button className="text-gray-900 dark:text-primary-500 dark:text-gray-50" variant="link">
                View more
              </Button>
            </div>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              Discover the latest makeup trends and products to enhance your natural beauty.
            </p>
          </div>
          <div className="group rounded-lg bg-white p-6 shadow-sm transition-all hover:shadow-md dark:bg-gray-800">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="h-12 w-12 rounded-full bg-[#EEF2FF] p-2.5 text-[#4F46E5] dark:bg-[#1F2937] dark:text-[#4F46E5]">
                  <SkullIcon className="h-7 w-7" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Skincare</h3>
              </div>
              <Button className="text-gray-900 dark:text-primary-500 dark:text-gray-50" variant="link">
                View more
              </Button>
            </div>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              Explore a wide range of skincare products to nourish and rejuvenate your skin.
            </p>
          </div>
          <div className="group rounded-lg bg-white p-6 shadow-sm transition-all hover:shadow-md dark:bg-gray-800">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="h-12 w-12 rounded-full bg-[#ECFDF5] p-2.5 text-[#10B981] dark:bg-[#1F2937] dark:text-[#10B981]">
                  <HashIcon className="h-7 w-7" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Hair</h3>
              </div>
              <Button className="text-gray-900 dark:text-primary-500 dark:text-gray-50" variant="link">
                View more
              </Button>
            </div>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              Find the perfect hair care products and services to keep your locks healthy and vibrant.
            </p>
          </div>
          <div className="group rounded-lg bg-white p-6 shadow-sm transition-all hover:shadow-md dark:bg-gray-800">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="h-12 w-12 rounded-full bg-[#FEF3C7] p-2.5 text-[#F59E0B] dark:bg-[#1F2937] dark:text-[#F59E0B]">
                  <HammerIcon className="h-7 w-7" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Nails</h3>
              </div>
              <Button className="text-gray-900 dark:text-primary-500 dark:text-gray-50" variant="link">
                View more
              </Button>
            </div>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              Discover the latest nail trends and treatments to keep your hands looking their best.
            </p>
          </div>
          <div className="group rounded-lg bg-white p-6 shadow-sm transition-all hover:shadow-md dark:bg-gray-800">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="h-12 w-12 rounded-full bg-[#E9F8F9] p-2.5 text-[#06B6D4] dark:bg-[#1F2937] dark:text-[#06B6D4]">
                  <BathIcon className="h-7 w-7" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Spas</h3>
              </div>
              <Button className="text-gray-900 dark:text-primary-500 dark:text-gray-50" variant="link">
                View more
              </Button>
            </div>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              Indulge in relaxing spa treatments and services to rejuvenate your mind and body.
            </p>
          </div>
          <div className="group rounded-lg bg-white p-6 shadow-sm transition-all hover:shadow-md dark:bg-gray-800">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="h-12 w-12 rounded-full bg-[#FEF2F2] p-2.5 text-[#EF4444] dark:bg-[#1F2937] dark:text-[#EF4444]">
                  <FlowerIcon className="h-7 w-7" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Fragrance</h3>
              </div>
              <Button className="text-gray-900 dark:text-primary-500 dark:text-gray-50" variant="link">
                View more
              </Button>
            </div>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              Explore a wide range of luxurious fragrances to enhance your personal style.
            </p>
          </div>
        </div>
      </div>
    </>
  )
}

function BathIcon(props:Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 6 6.5 3.5a1.5 1.5 0 0 0-1-.5C4.683 3 4 3.683 4 4.5V17a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5" />
      <line x1="10" x2="8" y1="5" y2="7" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <line x1="7" x2="7" y1="19" y2="21" />
      <line x1="17" x2="17" y1="19" y2="21" />
    </svg>
  )
}


function FlowerIcon(props:Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 7.5a4.5 4.5 0 1 1 4.5 4.5M12 7.5A4.5 4.5 0 1 0 7.5 12M12 7.5V9m-4.5 3a4.5 4.5 0 1 0 4.5 4.5M7.5 12H9m7.5 0a4.5 4.5 0 1 1-4.5 4.5m4.5-4.5H15m-3 4.5V15" />
      <circle cx="12" cy="12" r="3" />
      <path d="m8 16 1.5-1.5" />
      <path d="M14.5 9.5 16 8" />
      <path d="m8 8 1.5 1.5" />
      <path d="M14.5 14.5 16 16" />
    </svg>
  )
}


function HammerIcon(props:Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 12-8.5 8.5c-.83.83-2.17.83-3 0 0 0 0 0 0 0a2.12 2.12 0 0 1 0-3L12 9" />
      <path d="M17.64 15 22 10.64" />
      <path d="m20.91 11.7-1.25-1.25c-.6-.6-.93-1.4-.93-2.25v-.86L16.01 4.6a5.56 5.56 0 0 0-3.94-1.64H9l.92.82A6.18 6.18 0 0 1 12 8.4v1.56l2 2h2.47l2.26 1.91" />
    </svg>
  )
}


function HashIcon(props:Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="9" y2="9" />
      <line x1="4" x2="20" y1="15" y2="15" />
      <line x1="10" x2="8" y1="3" y2="21" />
      <line x1="16" x2="14" y1="3" y2="21" />
    </svg>
  )
}

type Props = {
  className: string
}
function PaintbrushIcon(props: Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18.37 2.63 14 7l-1.59-1.59a2 2 0 0 0-2.82 0L8 7l9 9 1.59-1.59a2 2 0 0 0 0-2.82L17 10l4.37-4.37a2.12 2.12 0 1 0-3-3Z" />
      <path d="M9 8c-2 3-4 3.5-7 4l8 10c2-1 6-5 6-7" />
      <path d="M14.5 17.5 4.5 15" />
    </svg>
  )
}


function SearchIcon(props:Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function SkullIcon(props:Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="9" cy="12" r="1" />
      <circle cx="15" cy="12" r="1" />
      <path d="M8 20v2h8v-2" />
      <path d="m12.5 17-.5-1-.5 1h1z" />
      <path d="M16 20a2 2 0 0 0 1.56-3.25 8 8 0 1 0-11.12 0A2 2 0 0 0 8 20" />
    </svg>
  )
}
